---
title: "stat418 final project"
author: "Shu Jiang"
date: "5/27/2019"
output:
  pdf_document: default
  html_document: default
---


```{r}
library(dplyr)
library(plotrix)
library(ggplot2)
library(car)
library(MASS)
#read csv file
movie<-read.csv('movie.csv')
#remove rows containing missing value
complete.cases(movie)
df<-movie[complete.cases(movie),]
str(df)
df<-na.omit(movie)
#remove unrelated and unrated movie level
newmovie<-df[which((df$Level == "PG") | (df$Level == "R") | (df$Level == "PG-13")), ]
attach(newmovie)
is.vector(newmovie$Genre)
Genre<-as.character(Genre)
genre1<-strsplit(Genre, split=" ")
class(genre1)
genre2<-unlist(genre1, use.names=FALSE)
class(genre2)
table(genre2)
freq <- data.frame(table(genre2))
freq$genre <- factor(freq$genre, levels = freq$genre[order(-freq$Freq)])
ggplot(freq, aes(x=genre, y=Freq)) + geom_bar(stat="identity")
#create new dummy variables
newmovie$Action<-vector(mode="numeric", length=5809)
for(i in 1:5809)
{
  newmovie$Action[i]<-ifelse("Action" %in% genre1[[i]], 1,0)
}

newmovie$Adventure<-vector(mode="numeric", length=5809)
for(i in 1:5809)
{
  newmovie$Adventure[i]<-ifelse("Adventure" %in% genre1[[i]], 1,0)
}

newmovie$Animation<-vector(mode="numeric", length=5809)
for(i in 1:5809)
{
  newmovie$Animation[i]<-ifelse("Animation" %in% genre1[[i]], 1,0)
}

newmovie$Biography<-vector(mode="numeric", length=5809)
for(i in 1:5809)
{
  newmovie$Biography[i]<-ifelse("Biography" %in% genre1[[i]], 1,0)
}

newmovie$Comedy<-vector(mode="numeric", length=5809)
for(i in 1:5809)
{
  newmovie$Comedy[i]<-ifelse("Comedy" %in% genre1[[i]], 1,0)
}

newmovie$Crime<-vector(mode="numeric", length=5809)
for(i in 1:5809)
{
  newmovie$Crime[i]<-ifelse("Crime" %in% genre1[[i]], 1,0)
}

newmovie$Drama<-vector(mode="numeric", length=5809)
for(i in 1:5809)
{
  newmovie$Drama[i]<-ifelse("Drama" %in% genre1[[i]], 1,0)
}

newmovie$Family<-vector(mode="numeric", length=5809)
for(i in 1:5809)
{
  newmovie$Family[i]<-ifelse("Family" %in% genre1[[i]], 1,0)
}

newmovie$Fantasy<-vector(mode="numeric", length=5809)
for(i in 1:5809)
{
  newmovie$Fantasy[i]<-ifelse("Fantasy" %in% genre1[[i]], 1,0)
}

newmovie$Film_Noir<-vector(mode="numeric", length=5809)
for(i in 1:5809)
{
  newmovie$Film_Noir[i]<-ifelse("Film-Noir" %in% genre1[[i]], 1,0)
}

newmovie$History<-vector(mode="numeric", length=5809)
for(i in 1:5809)
{
  newmovie$History[i]<-ifelse("History" %in% genre1[[i]], 1,0)
}

newmovie$Horror<-vector(mode="numeric", length=5809)
for(i in 1:5809)
{
  newmovie$Horror[i]<-ifelse("Horror" %in% genre1[[i]], 1,0)
}

newmovie$Music<-vector(mode="numeric", length=5809)
for(i in 1:5809)
{
  newmovie$Music[i]<-ifelse("Music" %in% genre1[[i]], 1,0)
}

newmovie$Musical<-vector(mode="numeric", length=5809)
for(i in 1:5809)
{
  newmovie$Musical[i]<-ifelse("Musical" %in% genre1[[i]], 1,0)
}

newmovie$Mystery<-vector(mode="numeric", length=5809)
for(i in 1:5809)
{
  newmovie$Mystery[i]<-ifelse("Mystery" %in% genre1[[i]], 1,0)
}

newmovie$Romance<-vector(mode="numeric", length=5809)
for(i in 1:5809)
{
  newmovie$Romance[i]<-ifelse("Romance" %in% genre1[[i]], 1,0)
}

newmovie$Sci_Fi<-vector(mode="numeric", length=5809)
for(i in 1:5809)
{
  newmovie$Sci_Fi[i]<-ifelse("Sci-Fi" %in% genre1[[i]], 1,0)
}

newmovie$Sport<-vector(mode="numeric", length=5809)
for(i in 1:5809)
{
  newmovie$Sport[i]<-ifelse("Sport" %in% genre1[[i]], 1,0)
}

newmovie$Thriller<-vector(mode="numeric", length=5809)
for(i in 1:5809)
{
  newmovie$Thriller[i]<-ifelse("Thriller" %in% genre1[[i]], 1,0)
}

newmovie$War<-vector(mode="numeric", length=5809)
for(i in 1:5809)
{
  newmovie$War[i]<-ifelse("War" %in% genre1[[i]], 1,0)
}

newmovie$Western<-vector(mode="numeric", length=5809)
for(i in 1:5809)
{
  newmovie$Western[i]<-ifelse("Western" %in% genre1[[i]], 1,0)
}
```

```{r}
#reclassify Duration
newmovie$new_Duration<-as.character(Duration)
newmovie$new_Duration<-strsplit(newmovie$new_Duration, split=" ")
for (i in 1:5809)
{
  newmovie$new_Duration[i]<-newmovie$new_Duration[[i]][1]
}
newmovie$new_Duration<-unlist(newmovie$new_Duration)
newmovie$new1duration<-as.integer(newmovie$new_Duration)
newmovie$final_Duration<-ifelse(newmovie$new1duration <= 100, "Short", ifelse(newmovie$new1duration >=101 & newmovie$new1duration <= 120, "Normal", "Long"))
table(newmovie$final_Duration)
```

```{r}
#reclassify Year
table(newmovie$Year)
newmovie$new_Year<-ifelse(newmovie$Year >= 1927 & newmovie$Year <= 1999, "before2000", ifelse(newmovie$Year >= 2000 & newmovie$Year <= 2010, "first_ten", "second_ten"))
table(newmovie$new_Year)
```


```{r}
#check normality of numerical variables and do log transformation to variables that are not normal
hist(newmovie$Score)
hist(newmovie$Votes)
newmovie$log_Votes<-log(newmovie$Votes+1)
hist(newmovie$log_Votes)
hist(newmovie$Gross_in_Million)
newmovie$log_gross<-log(newmovie$Gross_in_Million+1)
hist(newmovie$log_gross)
boxplot(newmovie$log_gross)
qqnorm(newmovie$log_gross)
```
```{r}
#set training data set and testing data set
set.seed(1)
t = sample(1:2000, 2000)
train = newmovie[t[1:1500],]
test = newmovie[t[1501:2000],]
newmovie<-train

```

```{r}
plot(lm(log_gross~log_Votes, data=newmovie))
outlierTest(lm(log_gross~log_Votes, data=newmovie))
influencePlot(lm(log_gross~log_Votes, data=newmovie))
plot(lm(log_gross~newmovie$Score, data=newmovie))
influencePlot(lm(log_gross~newmovie$Score, data=newmovie))
outlierTest(lm(log_gross~newmovie$Score, data=newmovie))  
```

```{r}
model<-lm(log_gross~new_Year+Level+final_Duration+Score+log_Votes+Action+Adventure+Animation+Biography+Comedy+Crime+Drama+Family+Fantasy+Film_Noir+History+Horror+Music+Musical+Mystery+Romance+Sci_Fi+Sport+Thriller+War+Western, data=newmovie)

summary(model)
plot(model)
influencePlot(model)
HighLeverage <- cooks.distance(model) > (4/nrow(newmovie))
LargeResiduals <- rstudent(model) > 3
datanml <- newmovie[!HighLeverage & !LargeResiduals,]
```


```{r}
model2<-lm(log_gross~new_Year+Level+final_Duration+Score+log_Votes+Action+Adventure+Animation+Biography+Comedy+Crime+Drama+Family+Fantasy+Film_Noir+History+Horror+Music+Musical+Mystery+Romance+Sci_Fi+Sport+Thriller+War+Western, data=datanml)
summary(model2)
```

```{r}
maic<-stepAIC(model2)
summary(maic)
plot(maic)
influencePlot(maic)
vif(maic)
#cross validation
mfinal<-lm(formula = log_gross ~ new_Year + Level + final_Duration + Score + log_Votes + Animation + Comedy + Drama + Family + Fantasy + History + Musical + Sci_Fi + Sport + War, data = test)
summary(mfinal)

```


```{r}
mbic<-stepAIC(model2, k = log(length(model2$residuals)))
summary(mbic)
plot(mbic)
vif(mbic)
#cross validation
mfinal2<-lm(formula = log_gross ~ new_Year + Level + final_Duration + Score + log_Votes + Animation + Comedy + Drama + Sport, data = test)
summary(mfinal2)
#mfinal2 this is our final model
```

```{r}
parameterset<-data.frame(new_Year="second_ten", Level="R", final_Duration="Long", Score=7.5, log_Votes=12.25, Animation=1, Comedy=0, Drama=1, Sport=0 )
result<-10^(predict(mfinal2, parameterset))
result



```